/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        // Core dark palette (Vercel/Supabase-inspired)
        "v-bg":       "#050505",
        "v-surface":  "#0f0f0f",
        "v-surface2": "#141414",
        "v-surface3": "#1a1a1a",
        "v-border":   "rgba(255,255,255,0.07)",
        "v-green":    "#3ecf8e",
        "v-green-dim":"rgba(62,207,142,0.12)",
        "v-text":     "#ffffff",
        "v-muted":    "rgba(255,255,255,0.55)",
        "v-dim":      "rgba(255,255,255,0.25)",
        "v-error":    "#ff4444",
        "v-amber":    "#f59e0b",
        "v-blue":     "#3b82f6",

        // Legacy Material Design tokens (kept for backward compat)
        "primary-fixed-dim": "#d2bbff",
        "outline": "#958da1",
        "on-secondary-fixed": "#1a1a2e",
        "surface-container-highest": "#34343d",
        "on-secondary-container": "#b8b6d0",
        "inverse-on-surface": "#302f39",
        "tertiary": "#c5c3e6",
        "tertiary-container": "#646482",
        "secondary-container": "#47475d",
        "on-error-container": "#ffdad6",
        "on-tertiary-fixed-variant": "#444461",
        "surface-variant": "#34343d",
        "on-tertiary-fixed": "#191933",
        "secondary-fixed": "#e2e0fc",
        "surface-container-lowest": "#0d0d16",
        "on-secondary": "#2f2e43",
        "error-container": "#93000a",
        "on-secondary-fixed-variant": "#45455b",
        "on-tertiary": "#2e2e49",
        "background": "#0a0a12",
        "secondary-fixed-dim": "#c6c4df",
        "secondary": "#c6c4df",
        "surface-dim": "#13131b",
        "on-surface-variant": "#ccc3d8",
        "on-primary-container": "#ede0ff",
        "on-error": "#690005",
        "inverse-surface": "#e4e1ed",
        "tertiary-fixed-dim": "#c5c3e6",
        "primary": "#d2bbff",
        "outline-variant": "#4a4455",
        "on-background": "#e4e1ed",
        "surface-container-high": "#292932",
        "tertiary-fixed": "#e2dfff",
        "surface": "#13131b",
        "primary-fixed": "#eaddff",
        "on-surface": "#e4e1ed",
        "surface-bright": "#393842",
        "on-tertiary-container": "#e5e3ff",
        "on-primary-fixed": "#25005a",
        "primary-container": "#7c3aed",
        "on-primary-fixed-variant": "#5a00c6",
        "on-primary": "#3f008e",
        "surface-tint": "#d2bbff",
        "surface-container": "#1f1f27",
        "surface-container-low": "#1b1b23",
        "error": "#ffb4ab",
        "inverse-primary": "#732ee4",
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "sans": ["Inter", "sans-serif"],
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        "full": "9999px"
      },
    },
  },
  plugins: [],
}
