# Generated by Django 4.2 on 2026-03-23 20:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('input_type', models.CharField(choices=[('text', 'Text'), ('url', 'URL')], max_length=10)),
                ('raw_input', models.TextField()),
                ('extracted_text', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('extracting', 'Extracting'), ('searching', 'Searching'), ('verifying', 'Verifying'), ('complete', 'Complete'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImageAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
                ('status', models.CharField(choices=[('analyzed', 'Analyzed'), ('skipped', 'Skipped'), ('failed', 'Failed')], default='analyzed', max_length=20)),
                ('is_ai_generated', models.BooleanField(blank=True, null=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('deepfake_probability', models.FloatField(blank=True, null=True)),
                ('indicators', models.JSONField(blank=True, default=list)),
                ('skip_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_analyses', to='verifier.verificationjob')),
            ],
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_text', models.TextField()),
                ('verdict', models.CharField(choices=[('true', 'True'), ('false', 'False'), ('partially_true', 'Partially True'), ('unverifiable', 'Unverifiable')], max_length=20)),
                ('confidence_score', models.FloatField()),
                ('reasoning', models.TextField()),
                ('sources', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='verifier.verificationjob')),
            ],
        ),
        migrations.CreateModel(
            name='AccuracyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_score', models.FloatField()),
                ('true_count', models.IntegerField(default=0)),
                ('false_count', models.IntegerField(default=0)),
                ('partially_true_count', models.IntegerField(default=0)),
                ('unverifiable_count', models.IntegerField(default=0)),
                ('ai_text_probability', models.FloatField(blank=True, null=True)),
                ('ai_text_indicators', models.JSONField(blank=True, default=list)),
                ('report_generated_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='verifier.verificationjob')),
            ],
        ),
    ]
