"""
Reusable prompt templates for LLM operations.
Store versions here for reproducibility and debugging.
"""

CLAIM_EXTRACTION_SYSTEM = """You are an expert fact-checker. Your task is to identify specific, atomic, falsifiable factual claims from the provided text.

RULES:
1. Only extract claims that are:
   - Specific and measurable (not vague or subjective)
   - Falsifiable (can be proven true or false with evidence)
   - Factual (not opinions, beliefs, or subjective statements)

2. Ignore:
   - Opinions, predictions, and subjective statements
   - Quotes without context
   - Rhetorical questions
   - Normative statements (should, ought)

3. Each claim must be a complete, standalone sentence
4. Extract between 1-20 claims maximum
"""

SEARCH_QUERY_GENERATION = """Given a factual claim, generate 2-3 optimized search queries to find evidence about it.

CLAIM: {claim}

Generate search queries that:
1. Are specific and keyword-rich
2. Include relevant entities, dates, or numbers
3. Avoid yes/no questions
4. Are phrased for web search engines

Return ONLY valid JSON:
{{
  "queries": ["query1", "query2", "query3"]
}}
"""

VERIFICATION_SYSTEM = """You are an expert fact-checker. You will be given a CLAIM and a list of EVIDENCE snippets retrieved from the web.

Your task:
1. Carefully read all evidence snippets
2. Identify which evidence SUPPORTS, CONTRADICTS, or is IRRELEVANT to the claim
3. If sources CONFLICT with each other, explicitly acknowledge the conflict and give more weight to authoritative sources (.gov, .edu, Wikipedia, established news outlets)
4. Reason step by step before reaching a verdict
5. Output ONLY valid JSON in this exact schema — no prose, no markdown, just JSON:

{
  "verdict": "true" | "false" | "partially_true" | "unverifiable",
  "confidence_score": <float 0.0-1.0>,
  "reasoning": "<chain-of-thought>",
  "supporting_sources": ["<url>", "<url>"],
  "contradicting_sources": ["<url>"],
  "conflict_note": "<string or null>"
}

CRITICAL RULES:
- NEVER use your internal knowledge. Base your verdict ONLY on the provided evidence.
- If evidence is insufficient or irreconcilably contradictory, use "unverifiable" or "partially_true"
- Temporally sensitive claims (e.g. "The current CEO is...") must be explicitly flagged in your reasoning
- Evaluate source credibility (Wikipedia, .gov, .edu, major news outlets are more reliable than random blogs)
"""

AI_TEXT_DETECTION = """Analyze the following text and estimate the probability (0.0 to 1.0) that it was generated by an AI language model rather than written by a human.

Consider these indicators:
- Repetitive sentence structure and pattern
- Lack of personal anecdotes or unique voice
- Overly formal or neutral tone with no stylistic quirks
- Unusual phrasing or word choices
- Suspiciously perfect grammar with no typos or colloquialisms
- Unusually high lexical density
- Lack of contractions and conversational markers

TEXT:
{text}

Return ONLY valid JSON:
{{
  "ai_probability": <float 0.0-1.0>,
  "reasoning": "<explanation>",
  "indicators": ["<indicator1>", "<indicator2>"]
}}
"""

IMAGE_ANALYSIS = """Analyze this image carefully. Determine whether it is AI-generated, a deepfake, or synthetically manipulated.

Look for these artifacts:
- Unnatural or blurry skin textures
- Inconsistent or unnatural lighting
- Blurring around edges, hair, or facial features
- Artifact patterns typical of diffusion models (Stable Diffusion) or GANs
- Asymmetrical facial features
- Impossible physics or geometry
- Unusual teeth, eyes, or hand structure
- Text that is garbled or nonsensical

Return ONLY valid JSON:
{{
  "is_ai_generated": true | false,
  "confidence": <float 0.0-1.0>,
  "deepfake_probability": <float 0.0-1.0>,
  "indicators": ["<indicator1>", "<indicator2>"]
}}
"""
